### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by sidewaiise** [ukrbublik/vectorious-plus#1]
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN bakery@0.0.1 No repository field.
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "vectorious-plus"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nblas-plus@1.2.15 install: `node-gyp configure && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nblas-plus@1.2.15 install script 'node-gyp configure && node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nblas-plus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nblas-plus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nblas-plus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by ukrbublik** [comment]
I haven't tested this package on OSX yet.
From logs it looks like **nblas-plus** (vectorious-plus is based on it) causes error. 
Can you please run `npm install nblas-plus` and write logs?

Probably, you have not **lapack** lib installed in your system. **blas** lib should be included in OSX already.
You can try to install **lapack** package with [**Homebrew**](http://brew.sh)

Or take a look on `.travis.yml` in repository, on `before_install` section.
Try to run these commands from terminal to build lapack by yourself:
```
   wget http://www.netlib.org/lapack/lapack-3.6.1.tgz
   tar xf lapack-3.6.1.tgz
   cd lapack-3.6.1/
   cmake -DCMAKE_INSTALL_PREFIX=/usr -DLAPACKE=ON -DCBLAS=ON -DBUILD_SHARED_LIBS=ON  .
   sudo make install -j2
   cd ..
```

**Comment by ukrbublik** [comment]
Please take a look at this instructions: 
https://github.com/ukrbublik/nblas-plus/blob/master/README.md#preinstall
You need to run this script before installation:
https://github.com/ukrbublik/nblas-plus/blob/master/preinstall/osx.sh
Tested on El Capitan.
Give a feedback please.
